### ISSUE TITLE
Standalone tmux-thumbs panics

### ISSUE THREAD

**Issue by tompreston** [fcsonline/tmux-thumbs#31]
Hey,
I can't get get the standalone tmux-thumbs to work. Maybe I'm using it wrong?

```bash
~$ cat /etc/fedora-release
Fedora release 32 (Thirty Two)

~$ cargo install thumbs

~$ tmux-thumbs
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/tpreston/.cargo/registry/src/github.com-1ecc6299db9ec823/thumbs-0.3.0/src/swapper.rs:218:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looks like `src/swapper.rs` expects to find `${dir}/target/release/thumbs` [here](https://github.com/fcsonline/tmux-thumbs/blob/master/src/swapper.rs#L204).

I think either:
- Remove tmux-thumbs from the crate install, because it's broken.
- Fix tmux-thumbs so it can run from anywhere. Why do we even need `dir` anyway? Can't we just assume tmux-thumbs is on the PATH?

Maybe there's a way to just use `thumbs` from tmux? Or do we need tmux-thumbs to do the pane swapping dance?

(btw I'm learning Rust atm, hopefully I can contribute once I've learned a bit more!)

**Comment by fcsonline** [comment]
Sorry, about the confusion, but yes you are using it wrong. I will try to clarify it.

There are two binaries in this package:
- `thumb`: This is the standalone version. This is the one that you want but it expects to get a pipe to work. Something like this `ifconfig | thumbs`. This will output the picked ip address, for example.
- `tmux-thumbs`: is a binary used by the tmux plugin and it is not designed to be execute it directly. It uses the standalone version underneath. It captures the tmux pane and it passes it as a pipe to the `thumbs` one. If you want to use it with tmux, follow the steps to install it.

Maybe the repository name is misleading, but this is for historical reasons. The project started as a tmux plugin but at some point, I saw an opportunity to create a standalone version for all those users that don't use tmux.

About the crash, maybe I can improve the message to avoid this wrong way of execution.

**Comment by tompreston** [comment]
Hey thanks, it was clear to me that `thumbs` was separate to `tmux-thumbs` - which is great btw.

My question was more about why `tmux-thumbs` in the [standalone thumbs crate](https://crates.io/crates/thumbs) doesn't work. I think you're saying it's just a left over and not supposed to be used like that - which is why I suggested either:
- Dropping it from the crate.
- Fixing it so that the tmux plugin uses the binaries installed by the crate.

I think it's broken because of a hardcoded path to `~/.tmux/plugins/tmux-thumbs/target/release/thumbs`. Which I think is why you pass in `--dir`. So my suggestion was to drop `--dir` and just expect `thumbs` and `tmux-thumbs` to be on the PATH - because they were already installed with cargo. 

So the install would become:
```
cargo install thumbs
git clone https://github.com/fcsonline/tmux-thumbs ~/.tmux/plugins/tmux-thumbs

# Add to shell
run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux
```

I guess it doesn't really matter! I'll just clone and build the plugin like the instructions say, for now. I'll make an MR with my suggestion later. Thanks! :smile:

**Comment by fcsonline** [comment]
If you want to use `tmux-thumbs` in your tmux instance, you need to **build it from the source code**. Maybe this is not clear enough in the README.

The crate way (`cargo install thumbs`) it was designed only for the standalone version (`thumbs`) because it represents that you don't use `tmux`. This is like this because the integration between `tmux` and this project requires this [shell script](https://github.com/fcsonline/tmux-thumbs/blob/master/tmux-thumbs.sh). You need this script to be present in someplace. When you install directly binaries from crates.io, you only get the binaries. This is a weird requirement from `tmux` :confused:. It only knows to execute shell scripts. 

For a better understanding of all the pieces in this project, those are the steps when you ask for hints in your terminal:

(your binding) -> `tmux-thumbs.sh` -> `tmux-thumbs` (swapper.rs) -> `thumbs` (main.rs, standalone version)

Maybe, the confusion comes, from the fact that you see a `tmux-thumbs` binary in your path. I don't know a way to avoid publishing this binary when I release a new version.

**Comment by tompreston** [comment]
Yep, I understand that you need to build it from source code within the tmux-thumbs plugin, I think this is [clear enough at the top of the README](https://github.com/fcsonline/tmux-thumbs#tmux-integration). I was getting confused because I saw the tmux-thumbs binary in my PATH. Thanks.
